### ISSUE TITLE
server_config.json  "enableDurability": false,   Does not seem to work in game.

### ISSUE THREAD

**Issue by joeyb276** [mornedhels/enshrouded-server#102]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Used image version

mornedhels/enshrouded-server:latest

### Used docker compose file or docker command

<img width="971" alt="image" src="https://github.com/user-attachments/assets/369b3318-9fff-4354-a7f0-3e7a3bfd5e66">

### What you expected to see, versus what you actually saw

When add all the new environment variables like described in the Code section. It seems SERVER_GS_ENABLE_DURABILITY works by editing the server_config.json. However, when in game the durabilty of weapons still goes down when using them. 

Does anyone else have this issue? And is a issue in the server image or with the game server in general?

**Comment by cp-fabian-pittroff** [comment]
Hey @joeyb276, what is the setting for the preset? For any kind of difficulty modification it has to be `Custom`.

**Comment by joeyb276** [comment]
> Hey @joeyb276, what is the setting for the preset? For any kind of difficulty modification it has to be `Custom`.

Ah nice, I had no idea you also has to use that variable. I picked and choose the ones I though would be nice for a return to the game due to the last update.

Thank you very much ^^. I notice my server now has a feather icon and my durability is gone.
