### ISSUE TITLE
Fall back to parsing the log for the player count

### ISSUE THREAD

**Issue by opello** [mornedhels/enshrouded-server#14]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

A rust implementation of a tool created to track currently connected users was posted in the Enshrouded Discord:  
https://github.com/jcjolley/enshrouded-player-count

It seems like either using this directly (if sufficient) or adopting the parsing logic put into it to track the player count locally instead of querying the Steam API might be nicer to avoid updating while players are connected.

As I was writing this up it occurred to me that it might be simpler to query the server directly (using the query port) but I haven't looked for an implementation of that yet.

**Comment by cp-fabian-pittroff** [comment]
Hey, thanks for the request. I could try to adopt it with my bash scripts. But I don't know how robust the logic is. It reads the service logs to count every join and exit of a user.

I hoped we get some kind of rcon, so I could get the information strait from that and also do server messaging, to alert users of an upcoming restart.

But I will try fiddling around with that and report back.

**Comment by opello** [comment]
Thanks for the image, it's been working quite well for me.

Using [python-a2s](https://github.com/Yepoleb/python-a2s) and a simple `python -c 'import a2s; print(len(a2s.players(("ip",port))));'` seems to work.  I tried in a python container alongside the enshrouded-server container, but I expect the "ip" being "127.0.0.1" would work too, if not SERVER_IP.

**Comment by cp-fabian-pittroff** [comment]
Thanks for the suggestion. I added the python-a2s script to check for connected players locally. I removed the `STEAM_*` env vars and added a `UPDATE_CHECK_PLAYERS` env to enable the check or not.

I'll test it a bit further and merge it afterwards.

**Comment by cp-fabian-pittroff** [comment]
@opello If you want you can check this feature with the latest `dev` or `dev-proton` image.

**Comment by cp-fabian-pittroff** [comment]
Released with version [0.4.0](https://github.com/mornedhels/enshrouded-server/releases/tag/0.4.0)
