### ISSUE TITLE
 [ enshrouded-server CreateBoundSocket: ::bind to port 0 returned error [no name available](10049)#015]

### ISSUE THREAD

**Issue by Simpuhl** [mornedhels/enshrouded-server#25]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Used image version

latest

### Used docker compose file or docker command

Compose file

### What you expected to see, versus what you actually saw

Keep getting this error, I doubt its related to your project but I thought i'd post it just in case or maybe someone has a clue why I get the error message.

### Logs from the container

2024-02-09 21:23:23.389 supervisord: message repeated 51 times: [ enshrouded-server CreateBoundSocket: ::bind to port 0 returned error [no name available](10049)#015]

**Comment by cp-fabian-pittroff** [comment]
Hey @Simpuhl, could you post your compose file and redact sensitive information? And also the enshrouded_server.json

**Comment by Simpuhl** [comment]
`version: "3"
name: enshrouded
services:
    enshrouded-server:
        container_name: enshrouded
        hostname: enshrouded
        network_mode: bridge
        restart: unless-stopped
        stop_grace_period: 30s
        ports:
            - 15636-15637:15636-15637/udp
        volumes:
            - /volume1/docker/enshrouded:/opt/enshrouded
        environment:
            - SERVER_NAME=XXX
            - SERVER_PASSWORD=XXX
            - SERVER_SLOT_COUNT=16
            - SERVER_PORT=15636
            - SERVER_QUERYPORT=15637
            - SERVER_IP=192.168.0.XXX
            - STEAM_API_KEY=0DF2EB46491FD58B2F085EA6235156FB
            - UPDATE_CRON=*/30 * * * *
            - PUID=XXXX
            - PGID=XXX
            - TZ=America/Los_Angeles
        image: mornedhels/enshrouded-server:latest`

**Comment by Simpuhl** [comment]
I did port forward and allow both 15636 & 15637 on firewall, ports show open when running port checker

**Comment by cp-fabian-pittroff** [comment]
hm, you have probably a problem with the `SERVER_IP`. Try resetting that to `0.0.0.0`.

**Comment by cp-fabian-pittroff** [comment]
And fyi `STEAM_API_KEY` is deprecated and is not used anymore. If you want the empty check you should use `UPDATE_CHECK_PLAYERS` `true` instead. And also check out the proton images. They seem to use less system resources.

**Comment by cp-fabian-pittroff** [comment]
Changing it to 0.0.0.0 basically allows binding to all available networks. So there are some usecases for that, but most of the time the default is fine.

**Comment by Simpuhl** [comment]
Ok I am going to set it to 0.0.0.0. remove steamapikey and add UPDATE_CHECK_PLAYERS=true

**Comment by Simpuhl** [comment]
I started getting this:

2024-02-09 22:34:03.156 supervisord: enshrouded-server [online] Server failed to connected to Steam 3

**Comment by cp-fabian-pittroff** [comment]
well one step further I guess. That could be a firewall problem. Do you have udp ports defined for your forwards and firewall rules? Do you have also outgoing firewall rules?

**Comment by Simpuhl** [comment]
> well one step further I guess. That could be a firewall problem. Do you have udp ports defined for your forwards and firewall rules? Do you have also outgoing firewall rules?

I was always able to connect before. I already added the ports in firewall and forwarded on router. I've been playing fine for a few days other than that error message prior.

Maybe I just remove the line all together for the IP and let it do its default?

**Comment by Simpuhl** [comment]
Let me try that

**Comment by Simpuhl** [comment]
Looks like it's working again. Thank you sir
