### ISSUE TITLE
SERVER_IP

### ISSUE THREAD

**Issue by SaschMie** [mornedhels/enshrouded-server#4]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

What is this exactly doing? Is that the external or internal ip? My docker is up and running but i cant find it in the server list, even if the logs said its connected and up (ports are open and correct). So i guess its maybe something with this ip thing, actual its empty.

**Comment by cp-fabian-pittroff** [comment]
Hey, this env var just sets the ip in the enshrouded_server.json. The ip is only for binding to the right network and can most likely ignored.

You can read more about the available configs here ([Enshrouded Docs](https://enshrouded.zendesk.com/hc/en-us/articles/16055441447709-Dedicated-Server-Configuration))

When you leave it empty, the default will be used (0.0.0.0) which binds to all networks or basically allow all incoming connections.

Have you tried to find the server with the steam servers list? (Steam -> View -> Servers) If you can't find your server listed there, you can try to manually add the ip on the same window. If it doesn't show you your server, you probably have a firewall issue.

If the server runs on the same network (locally), than it might be a dns-rebind-issue of your router. In that case, could you check if someone else can access the server?

**Comment by brettinternet** [comment]
Does `SERVER_IP` and `STEAM_API_PUBLIC_IP` accept a FQDN such as `ip.example.com` to resolve the IP?

**Comment by cp-fabian-pittroff** [comment]
Just verified, both need to be valid ipv4 addresses. The`STEAM_API_PUBLIC_IP` is only relevant for the update cron, to check if the server is empty. 

I should update my docs to clarify that.

**Comment by coute** [comment]
Hello @cp-fabian-pittroff , i have the same problem with the server. The server is launched and registered on Steam.
```
2024-01-25 12:08:02.818 supervisord: enshrouded-server [online] Server connected to Steam successfully
2024-01-25 12:08:03.126 supervisord: enshrouded-server [online] Server is not VAC Secure!
2024-01-25 12:08:03.127 supervisord: enshrouded-server [online] Server SteamId: 90179864601901064
2024-01-25 12:08:03.127 supervisord: enshrouded-server [online] Public ipv4: 62.210.88.96
```

But when i'm in the game and searching for the server, i can't find it. I think it's an issue with the game, that is not able to retrieve all servers with the Steam API.
When i query the Steam API, the server is available :

```bash
curl -sX GET "https://api.steampowered.com/IGameServersService/GetServerList/v1/?key=**REDACTED**&filter=addr\\62.210.88.96:15637"
{"response":{"servers":[{"addr":"62.210.88.96:15637","gameport":15636,"steamid":"90179864601901064","name":"crazyhorde","appid":1203620,"gamedir":"Enshrouded","version":"0.0.15.0","product":"Enshrouded","region":-1,"players":0,"max_players":16,"bots":0,"secure":false,"dedicated":true,"os":"w","gametype":"1;487046"}]}}
```

**Comment by cp-fabian-pittroff** [comment]
Jeah, they hotfixed the server browser yesterday. It is now limited to about 50 I think. You should find your server directly in the steam servers browser (Steam -> View -> Servers) and mark it as a favorite ([Docs](https://enshrouded.zendesk.com/hc/en-us/articles/16056312924957-Dedicated-Server-FAQ))

PS: I removed your public IP & steamid from the comment.

**Comment by cp-fabian-pittroff** [comment]
@coute I can't find it in steam either. Is the server still running?

**Comment by coute** [comment]
Yes. The server is running.

**Comment by cp-fabian-pittroff** [comment]
Hm, thats very odd. Maybe try restarting the server and double check if there is any firewall blocking incoming packages (udp).

If it is a homeserver scenario, also check if you forwarded both udp ports to the server.

**Comment by SaschMie** [comment]
Strangely mine is now in the list, but another one from gportal not. Seems to be some issue with the server browser of the game to me

**Comment by cp-fabian-pittroff** [comment]
@MrSnake0208 could you tell me your server name, so I can try to find it?

And also double check if there is some firewall or forwarding issue on the server network.

**Comment by coute** [comment]
No issue with the firewall
```bash
nc -v -u 62.210.88.96 15637
Ncat: Version 7.70 ( https://nmap.org/ncat )
Ncat: Connected to 62.210.88.96:15637.

nc -v -u 62.210.88.96 15638
Ncat: Version 7.70 ( https://nmap.org/ncat )
Ncat: Connected to 62.210.88.96:15638.
```

**Comment by MrSnake0208** [comment]
> @MrSnake0208 could you tell me your server name, so I can try to find it?
> 
> And also double check if there is some firewall or forwarding issue on the server network.

Yahu Farm

**Comment by cp-fabian-pittroff** [comment]
> No issue with the firewall
> 
> ```shell
> nc -v -u ***.***.***.*** 15637
> Ncat: Version 7.70 ( https://nmap.org/ncat )
> Ncat: Connected to ***.***.***.***:15637.
> 
> nc -v -u ***.***.***.*** 15638
> Ncat: Version 7.70 ( https://nmap.org/ncat )
> Ncat: Connected to ***.***.***.***:15638.
> ```

you use 15637 and 8? In the steamapi it returns 15636 for the gameport and 7 for query.

**Comment by MrSnake0208** [comment]
> > No issue with the firewall
> > ```shell
> > nc -v -u ***.***.***.*** 15637
> > Ncat: Version 7.70 ( https://nmap.org/ncat )
> > Ncat: Connected to ***.***.***.***:15637.
> > 
> > nc -v -u ***.***.***.*** 15638
> > Ncat: Version 7.70 ( https://nmap.org/ncat )
> > Ncat: Connected to ***.***.***.***:15638.
> > ```
> 
> you use 15637 and 8? In the steamapi it returns 15636 for the gameport and 7 for query.

I use 37304 and 38304 because share the device with others and i can't use 15636 and 15637

**Comment by coute** [comment]
ports:
      - "15636:15636/udp"
      - "15637:156**6**7/udp"
      
      I'm a monkey !

**Comment by coute** [comment]
An other thing to fix because i'm using **swarm**, set the host mode : 
```
      - target: 15636
        published: 15636
        protocol: "udp"
        mode: "host"
      - target: 15637
        published: 15637
        protocol: "udp"
        mode: "host"
```

**Comment by cp-fabian-pittroff** [comment]
@MrSnake0208 I tested it with a second enshrouded server. It seems, I can only find one server. The other sever returns the same same query and gameport for a different steamid. Not sure why though

Do you have another server running on the same public ip?

**Comment by cp-fabian-pittroff** [comment]
oh well, I might have the problem - give me a sec

**Comment by coute** [comment]
After to have fixed ports, i still have the same problem.

**Comment by cp-fabian-pittroff** [comment]
found the problem. For now don't use the `SERVER_PORT` and `SERVER_QUERYPORT` variables. They add an unintended " and that breaks the enshrouded server logic.

For now just remove the env vars and set the ports manually in the enshrouded_server.json without the ".

I will prepare a fix, after I did some more testing.

**Comment by coute** [comment]
Ok. Thannks.

**Comment by MrSnake0208** [comment]
> found the problem. For now don't use the `SERVER_PORT` and `SERVER_QUERYPORT` variables. They add an unintended " and that breaks the enshrouded server logic.发现了问题。暂时不要使用 `SERVER_PORT` 和 `SERVER_QUERYPORT` 变量。它们会添加一个意外的""，从而破坏服务器的逻辑。
> 
> For now just remove the env vars and set the ports manually in the enshrouded_server.json without the ".现在，只需删除 env vars，并在 enshrouded_server.json 中手动设置端口，而不去掉"......"。
> 
> I will prepare a fix, after I did some more testing.等我再做一些测试后，我会准备一个修复方案。

It's done. Thx!!

**Comment by cp-fabian-pittroff** [comment]
fix is available with the current dev branch. I will add some more changes and publish a new release later today.

**Comment by coute** [comment]
Fixed for me. It was a firewall issue. My bad.
