### ISSUE TITLE
inject a game save

### ISSUE THREAD

**Issue by KissKool-63** [mornedhels/enshrouded-server#42]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Feature description

How do I inject a game save? I tried to transfer some files but I must not take the right ones (3ad85aea) because it doesn't work.
pls help me :(

**Comment by cp-fabian-pittroff** [comment]
Hey @KissKool-63,
for it to work you need to shutdown the server. And add the `3ad85aea` file into the `game/server/savegame` folder (default). If there are any other files. Just make a backup if you need them or remove them.

After that, just start the server.

**Comment by KissKool-63** [comment]
this is what i was doing but it didn't work, i forgot to adjust the rights on the file. now it works! thanks
