### ISSUE TITLE
[online] Server failed to connected to Steam 3

### ISSUE THREAD

**Issue by MrSnake0208** [mornedhels/enshrouded-server#5]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Used image version

sha256:8e22ede2229b4149338006cafee5eb2becd278cabcb9cc38c107374a83e9b3d4

### Used docker compose file or docker command

docker run\
  -d\
  --name enshrouded \
  --restart=unless-stopped \
  -p 37304:37304/udp  \
  -p 38304:38304/udp  \
  -v ./game:/opt/enshrouded  \
  -e SERVER_NAME="Yahu Farm"  \
  -e SERVER_PASSWORD="123" \
  -e UPDATE_CRON="*/30 * * * *" \
  -e PUID=4711  \
  -e PGID=4711  \
  -e SERVER_PORT=37304  \
  -e SERVER_QUERYPORT=38304  \
  -e SERVER_IP=MyServerIP  \
  -e STEAM_API_PUBLIC_IP=MyServerIP  \
  --env=HTTPS_PROXY="http://172.17.0.4:7890" \
  --env=HTTP_PROXY="http://172.17.0.4:7890" \
  --env=https_proxy="http://172.17.0.4:7890" \
  --env=http_proxy="http://172.17.0.4:7890"  \
 mornedhels/enshrouded-server:latest

### What you expected to see, versus what you actually saw

When I set STEAM_API_PUBLIC_IP and SERVER_IP to my server IP, it keeps showing [online] Server failed to connect to Steam 3.

**Comment by cp-fabian-pittroff** [comment]
`SERVER_IP` is the ip config inside the `enshrouded_server.json`. So the network ip to bind to (in most cases you don't have to change that value at all). If you already set the env you have to update the config manually. 

path: game/server/enshrouded_server.json

Default value is `0.0.0.0` (bind/listen to all networks)

Pls check if that solves the problem.

**Comment by MrSnake0208** [comment]
> `SERVER_IP` is the ip config inside the `enshrouded_server.json`. So the network ip to bind to (in most cases you don't have to change that value at all). If you already set the env you have to update the config manually.
> 
> path: game/server/enshrouded_server.json
> 
> Default value is `0.0.0.0` (bind/listen to all networks)
> 
> Pls check if that solves the problem.

Thx, I change it to 0.0.0.0 and worked but can't find server like another issue "SERVER_IP"

**Comment by cp-fabian-pittroff** [comment]
great, than we use #4 for the other problem.

I will leave this issue open, to remind me to update the readme.
