### ISSUE TITLE
SERVER_PORT variable removed?

### ISSUE THREAD

**Issue by faandg** [mornedhels/enshrouded-server#74]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Question

Coming back to the game after a bit, was re-aligning my config and noticed the SERVER_PORT was removed?
Found this commit but no notes why the removal took place 
https://github.com/mornedhels/enshrouded-server/pull/56/commits/3a7df26d1e6e2098e992be00a51c764c912b0d59
I was wondering why?

**Comment by cp-fabian-pittroff** [comment]
Hey @faandg,
well there is no official note on the changelogs, but on their docs for the server they mentioned the removal of that port.

https://enshrouded.zendesk.com/hc/en-us/articles/19191581489309-Server-Roles-Configuration#h_01HZ29QC64ANFG7N4X39XRZ1MK

The environment variable is ignored and you only need to open the queryport in your firewall and docker config.

**Comment by faandg** [comment]
@cp-fabian-pittroff alright, thanks for the clarification!
